### ISSUE TITLE
Drehgeschswindigkeit beim Abspielen an die Aufnahmegeschwindigkeit koppeln

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#10]
Drehgeschswindigkeit beim Abspielen(d. Neubr. Videos) an die Aufnahmegeschwindigkeit (d. neuen Videos) koppeln
* jeder x.Tick der ein (Neubronner) Bild liefert setzt einen timestamp um später die richtigen Bilder zu einem neuen Video zusammenzuführen
* zum Schluss gibt es genauso viele "neue" Bilder wie "alte"

**Comment by aschle** [comment]
![img_0615](https://cloud.githubusercontent.com/assets/883797/7866970/432853b4-0573-11e5-9dc9-668a1bffd6e6.JPG)
