### ISSUE TITLE
Durch Drehung des Encoder Bilder durchschalten können

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#11]
Mischung aus 3 und 4

**Comment by aschle** [comment]
es klappt, problem ist aber das wenn man ganz schnell dreht, die bilder nicht sonderlich schneller durchgeschalten werden, also so richtig richtig schnell funktioniert das nicht

**Comment by aschle** [comment]
auch das problem wurde behoben,
danke an @lbenedix  ... einfach die auflösung von dem raspi runtersetzen
gibt ein neues issue für

hm oder doch nicht
