### ISSUE TITLE
Herausfinden wie groß Vollbildmodus sein soll.

### ISSUE THREAD

**Issue by aschle** [aschle/magicKurbelKamera#12]
352px X 244px ist die aktuelle größe der Bilder.
Die Frage ist wie groß die Bilder werden sollen, ich will sie ja nicht verzerren.
Vollbild ist ja immer abhängig vom Bildschirm den man hat.

Die Bilder haben ein Aspect Ratio[1] von 88 : 61.

[1] http://andrew.hedges.name/experiments/aspect_ratio/

**Comment by lbenedix** [comment]
Da das bild eher 4:3 als 16:9 ist, wüde ich das in der Höhe maximieren und rechts und links schwarze Balken haben.

Muss man die Bilder vor dem Anzeigen resizen oder kann man das einfach skalieren?

**Comment by aschle** [comment]
kann man skalieren

**Comment by aschle** [comment]
4:3 ist z.B. 1024x768, das ist doch erstmal ok, oder? der beamer macht das doch dann eh größer oder?

**Comment by lbenedix** [comment]
Reicht!

On 1. Juni 2015 18:34:55 MESZ, Alexa Schlegel <notifications@github.com> wrote:
>4:3 ist z.B. 1024x768, das ist doch erstmal ok, oder? der beamer macht
>das doch dann eh größer oder?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aschle/magicKurbelKamera/issues/12#issuecomment-107629061

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
