### ISSUE TITLE
State Maschine abbilden

### ISSUE THREAD

**Issue by aschle** [aschle/magicKurbelKamera#14]
main loop ist endlosschleife
es gibt eine Zustandvariable, diese wird gesetzt
am besten ein switch

**Comment by aschle** [comment]
5h

**Comment by lbenedix** [comment]
Hier der aktuelle Prototype-Code: https://github.com/aschle/magicKurbelKamera/blob/master/pygame_keypress/test_keypress.py

**Comment by lbenedix** [comment]
Wir lassen es bei der Struktur, die durch pygame vorgegeben ist, auch wenn das vielleicht nicht die reine Lehre ist
