### ISSUE TITLE
MagicTimestamps beim Aufnehmen speichern

### ISSUE THREAD

**Issue by aschle** [aschle/magicKurbelKamera#15]
in einer schönen Liste

**Comment by lbenedix** [comment]
Wenn eine der beiden Pfeiltasten gedrückt wird, die Zeit seit dem letzten Tastendruck in einem Array abspeichern.

Zeit seit Programmstart: pygame.time.get_ticks()

**Comment by lbenedix** [comment]
ist noch beim Abspielen drin, müsste noch an die richtige Stelle refactored werden (Wenn die Statemachine fertig ist)
