### ISSUE TITLE
Aus Einzelbildern und MagicTimestamps ein Video machen bauen [keinGIF]

### ISSUE THREAD

**Issue by aschle** [aschle/magicKurbelKamera#16]
neubronnerbilder nehmen und dummyArray
und gif bauen
schauen wie man ein GIF baut

**Comment by lbenedix** [comment]
https://stackoverflow.com/questions/753190/programmatically-generate-video-or-animated-gif-in-python

**Comment by lbenedix** [comment]
https://visvis.googlecode.com/hg/vvmovie/images2gif.py

**Comment by aschle** [comment]
bei mir hat es nur mit `PIL` funktioniert nicht mit `PILLOW`.
es war auch ein bischen ein hin und her die richtigen libraries zu installieren!!!

das hat funktioniert:
`pip install PIL --allow-external PIL --allow-unverified PIL`

ich hab mich einfach hier orientiert:
http://stackoverflow.com/questions/13041893/generating-an-animated-gif-in-python

wenn man alle X Bilder verwendet sagt er:
`IOError: [Errno 24] Too many open files: 'NEUBR_28_1022.jpg'

Es werden erstmal aus einem vordefinierten Set an Bildern ein GIF erstellt, noch nix mit magicTimestamp und so, kommt aber noch.
`

**Comment by aschle** [comment]
hier ist der code:
https://github.com/aschle/magicKurbelKamera/tree/images2gif

**Comment by lbenedix** [comment]
Eventuell sollten wir ein init_script anlegen, mit dem das ganze Zeug, dass man machen muss, bevor man mit der magicKurbelKamera Spaß haben kann

**Comment by lbenedix** [comment]
Wo ist dein erstelltes gif? 
![Pics or it didn't happen](http://pixel-pushers-book.com/wp-content/uploads/2015/03/pics_or_it_didnt_happen_retro_tshirt-p235350460184511443qj9v_328_zpsa77184e3.jpg)

**Comment by lbenedix** [comment]
Eventuell kann man das gif auch mit ImageMagick erzeugen, falls die anzahl der Frames tatsächlich ein Problem ist:
http://www.imagemagick.org/Usage/anim_basics/#gif_anim

**Comment by aschle** [comment]
https://github.com/aschle/magicKurbelKamera/blob/10aa3ebeb100534de30b3884004af77e385fd3a9/video/frames/test.gif

**Comment by aschle** [comment]
ja das wäre die alternative dann, ich schätze auch das das besser ist, aber dann muss man den krams auch wieder installieren :(

**Comment by lbenedix** [comment]
ist Imagemagick nicht sowieso installiert?

**Comment by lbenedix** [comment]
Falls gif doof ist vielleicht doch ffmpeg:

https://superuser.com/questions/624567/ffmpeg-create-a-video-from-images#12160155

**Comment by lbenedix** [comment]
http://owenashurst.com/?p=242

**Comment by lbenedix** [comment]
http://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/
