### ISSUE TITLE
GIF hochladen bei Dropbox

### ISSUE THREAD

**Issue by aschle** [aschle/magicKurbelKamera#18]
* API rausfinden
* wie läd man was hoch
* was ist der LINK

**Comment by lbenedix** [comment]
https://www.dropbox.com/developers/core/start/python

**Comment by lbenedix** [comment]
http://raspi.tv/2013/how-to-use-dropbox-with-raspberry-pi

**Comment by kajaT** [comment]
:) Lukas hat schon den passenden Link gepostet: 
http://raspi.tv/2013/how-to-use-dropbox-with-raspberry-pi
der erklärt wirklich alles Schritt für Schritt

**Comment by aschle** [comment]
wenn Dropbox doch zu kompliziert/aufwändig ist, dann sieht google drive eigentlich ganz einfach aus:
https://pypi.python.org/pypi/PyDrive
