### ISSUE TITLE
Mohren tanzt zerschneiden

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#2]

**Comment by lbenedix** [comment]
https://stackoverflow.com/questions/8287759/extracting-frames-from-mp4-flv

**Comment by lbenedix** [comment]
ffmpeg -ss 00:00:08 -i NEUBR_28_DL_moren_tanzt_x264.mp4 -r 16.0 frames/NEUBR_28_%4d.jpg
