### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by aschle** [aschle/magicKurbelKamera#25]
Sollte irgendwie so aussehen:
https://pip.readthedocs.org/en/1.1/requirements.html

     dropbox
     pyqrcode
     pypng
     pil

**Comment by lbenedix** [comment]
Kann aus prepare_system.sh entnommen werden

On 11. Juni 2015 12:18:55 MESZ, Alexa Schlegel <notifications@github.com> wrote:
>Sollte irgendwie so aussehen:
>https://pip.readthedocs.org/en/1.1/requirements.html
>
>     dropbox
>     pyqrcode
>     pypng
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aschle/magicKurbelKamera/issues/25

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by aschle** [comment]
da hab ich das her, nur in der stehen ja noch lauter andere ding, dachte eher das man es trennt

**Comment by lbenedix** [comment]
Jepp macht Sinn

On 11. Juni 2015 12:50:04 MESZ, Alexa Schlegel <notifications@github.com> wrote:
>da hab ich das her, nur in der stehen ja noch lauter andere ding,
>dachte eher das man es trennt
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aschle/magicKurbelKamera/issues/25#issuecomment-111083492

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
