### ISSUE TITLE
Bilder im Vollbildmodus im gleichen Fenster per Tastendruck hintereinander durchschalten

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#3]
(Anzahl der Ticks pro Drehung)/8 = normale Geschwindigkeit
(2 Drehungen pro Sekunde)
jeder x.Tick ein Bild

**Comment by lbenedix** [comment]
http://answers.opencv.org/question/24666/iterating-through-a-video-frame-by-frame/

**Comment by lbenedix** [comment]
https://stackoverflow.com/questions/6997419/how-to-create-a-loop-to-read-several-images-in-a-python-script

**Comment by lbenedix** [comment]
https://stackoverflow.com/questions/19285562/python-opencv-imread-displaying-image

**Comment by lbenedix** [comment]
https://stackoverflow.com/questions/21983062/in-python-opencv-is-there-a-way-to-quickly-scroll-through-frames-of-a-video-all

**Comment by lbenedix** [comment]
https://www.pkimber.net/howto/python/modules/pillow.html

**Comment by lbenedix** [comment]
https://github.com/python-pillow/Pillow/blob/master/Scripts/gifmaker.py

**Comment by aschle** [comment]
* https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=11990
* http://stackoverflow.com/questions/24027462/simple-example-of-displaying-an-image-fullscreen-in-python

**Comment by aschle** [comment]
Bilder auf fullscreen vergrößern:
http://stackoverflow.com/questions/20002242/how-to-scale-images-to-screen-size-in-pygame

**Comment by aschle** [comment]
ich würde das hier auch schließen oder
@lbenedix ?
