### ISSUE TITLE
Wieviele Ticks pro Drehung erkennt der Raspberry Pi

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#4]

**Comment by kajaT** [comment]
(Anzahl der Ticks pro Drehung)/8 = normale Geschwindigkeit
(2 Drehungen pro Sekunde)
jeder x.Tick ein Bild

**Comment by aschle** [comment]
es sind zwischen 45 und 55 events pro sekunde, so genau lässt sich das nicht sagen
