### ISSUE TITLE
Statemachine aufmalen

### ISSUE THREAD

**Issue by lbenedix** [aschle/magicKurbelKamera#5]
Da unsere Architektur eine Eventloop (siehe Processing loop()-funktion) ist, müssen die Zustände und die Zustandswechsel aufgemalt werden.

**Comment by lbenedix** [comment]
https://en.wikipedia.org/wiki/Finite-state_machine

**Comment by aschle** [comment]
![201505300209_statemaschine](https://cloud.githubusercontent.com/assets/883797/7894767/07332ec0-0671-11e5-8e3c-2000f99ac6c3.jpg)

**Comment by lbenedix** [comment]
Hier das digitalisierte Diagram:
https://docs.google.com/drawings/d/1c6Arh_p0eZYdnNagO-bWfo2evbyZkbReI3UGyPWo8tg/edit
