### ISSUE TITLE
Aufnahme: Raspi mit Python durch Tastendruck zum aufnehmen bringen

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#6]

**Comment by lbenedix** [comment]
https://www.raspberrypi.org/picamera-pure-python-interface-for-camera-module/

**Comment by lbenedix** [comment]
http://www.raspberrypi-spy.co.uk/2013/05/capturing-hd-video-with-the-pi-camera-module/

**Comment by lbenedix** [comment]
Hier hat mal jemand das mit den Einzelbildern (Photo statt Video) versucht und in den Kommentaren ist jemand auf 1.7Frames/s gekommen: https://www.raspberrypi.org/forums/viewtopic.php?t=50075&p=403012 klingt aber kompliziert
