### ISSUE TITLE
Aufnehmen

### ISSUE THREAD

**Issue by kajaT** [aschle/magicKurbelKamera#8]
-> einrasten oder nicht: diskutieren

**Comment by aschle** [comment]
das event des Knopfdrückens wird abgefangen, aktuell wird ein Foto gemacht
man sollte in den Zustand PRE_REC gehen

**Comment by lbenedix** [comment]
Einzelbilder von der Kamera abspeichern:

https://picamera.readthedocs.org/en/release-1.10/recipes2.html#rapid-capture-and-processing

**Comment by lbenedix** [comment]
Bei Druck auf die "r" Taste wird in einem parallelen Prozess/Thread ein Video aufgenommen (natürlich als einzelne jpg-Frames). 

Framerate und Dauer der Aufnahme sind dabei als globale Variablen oben im Script abgelegt.

Es ist sichergestellt, dass nur eine Aufnahme parallel läuft und sich auch keine Queue bildet, wenn man während der Aufnahme nochmal den Button drückt.

**Comment by lbenedix** [comment]
Hier ist der Code dazu: https://github.com/aschle/magicKurbelKamera/blob/master/pygame_keypress/test_keypress.py

**Comment by lbenedix** [comment]
http://stackoverflow.com/questions/17809409/how-to-start-kill-application-with-python-script

**Comment by lbenedix** [comment]
http://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/
